name: calender
services:
  web:
    image: web.calender
    build:
      context: ../
      dockerfile: .docker/dockerfile
    container_name: web.calender
    restart: always
    ports:
      - "5173:5173"
